events {}

http {
    # Servidor com o seu dominio (api.stheeisaque.com)
    server {
        listen 80;
        server_name api.stheeisaque.com;

        # Rota do Cardapio no seu dominio oficial
        location /cardapio-api/ {
            rewrite ^/cardapio-api/(.*) /$1 break;
            proxy_pass http://host.docker.internal:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API do Controle Financeiro Pessoal (Container Docker 128MB)
        location /finance-api/ {
            rewrite ^/finance-api/(.*) /$1 break;
            proxy_pass http://financeiro_backend:3006;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass http://host.docker.internal:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Servidor Default (Acesso direto pelo IP da VM)
    server {
        listen 80 default_server;

        # API do Cardapio Digital (Boteco do Sivirino)
        location /cardapio-api/ {
            rewrite ^/cardapio-api/(.*) /$1 break;
            proxy_pass http://host.docker.internal:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API do Controle Financeiro Pessoal (Container Docker 128MB)
        location /finance-api/ {
            rewrite ^/finance-api/(.*) /$1 break;
            proxy_pass http://financeiro_backend:3006;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Plataforma Ingles
        location /plataforma-ingles/ {
            rewrite ^/plataforma-ingles/(.*) /$1 break;
            proxy_pass http://host.docker.internal:3003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ByteData Frontend (Default)
        location / {
            proxy_pass http://host.docker.internal:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
